"""Names of the `resolve.*` enum constants documented in Blackmagic's README.

The fusionscript proxy does not enumerate them (`dir(resolve)` comes back
empty of constants - live-verified on Resolve 21.0.4), but `getattr` works.
So /system/constants probes this list instead of introspecting."""

from __future__ import annotations

EXPORT_TYPES = [
    "EXPORT_AAF", "EXPORT_DRT", "EXPORT_EDL", "EXPORT_FCP_7_XML", "EXPORT_FCPXML_1_8", "EXPORT_FCPXML_1_9",
    "EXPORT_FCPXML_1_10", "EXPORT_HDR_10_PROFILE_A", "EXPORT_HDR_10_PROFILE_B", "EXPORT_TEXT_CSV", "EXPORT_TEXT_TAB",
    "EXPORT_DOLBY_VISION_VER_2_9", "EXPORT_DOLBY_VISION_VER_4_0", "EXPORT_DOLBY_VISION_VER_5_1", "EXPORT_OTIO",
    "EXPORT_ALE", "EXPORT_ALE_CDL",
]
EXPORT_SUBTYPES = ["EXPORT_NONE", "EXPORT_AAF_NEW", "EXPORT_AAF_EXISTING", "EXPORT_CDL", "EXPORT_SDL", "EXPORT_MISSING_CLIPS"]
KEYFRAME_MODES = ["KEYFRAME_MODE_ALL", "KEYFRAME_MODE_COLOR", "KEYFRAME_MODE_SIZING"]
CACHE_MODES = ["CACHE_AUTO_ENABLED", "CACHE_DISABLED", "CACHE_ENABLED"]
MARKER_COLORS = [
    f"MARKER_{c}"
    for c in ("BLUE", "CYAN", "GREEN", "YELLOW", "RED", "PINK", "PURPLE", "FUCHSIA", "ROSE", "LAVENDER", "SKY", "MINT", "LEMON", "SAND", "COCOA", "CREAM")
]
SUBTITLE_KEYS = ["SUBTITLE_LANGUAGE", "SUBTITLE_CAPTION_PRESET", "SUBTITLE_CHARS_PER_LINE", "SUBTITLE_LINE_BREAK", "SUBTITLE_GAP"]
AUTO_CAPTION = [
    f"AUTO_CAPTION_{l}"
    for l in (
        "AUTO", "DANISH", "DUTCH", "ENGLISH", "FRENCH", "GERMAN", "ITALIAN", "JAPANESE", "KOREAN", "MANDARIN_SIMPLIFIED",
        "MANDARIN_TRADITIONAL", "NORWEGIAN", "PORTUGUESE", "RUSSIAN", "SPANISH", "SWEDISH", "SUBTITLE_DEFAULT", "TELETEXT",
        "NETFLIX", "LINE_SINGLE", "LINE_DOUBLE",
    )
]
AUDIO_SYNC = [
    "AUDIO_SYNC_MODE", "AUDIO_SYNC_CHANNEL_NUMBER", "AUDIO_SYNC_RETAIN_EMBEDDED_AUDIO", "AUDIO_SYNC_RETAIN_VIDEO_METADATA",
    "AUDIO_SYNC_WAVEFORM", "AUDIO_SYNC_TIMECODE", "AUDIO_SYNC_CHANNEL_AUTOMATIC", "AUDIO_SYNC_CHANNEL_MIX",
]
LUT_EXPORT = ["EXPORT_LUT_17PTCUBE", "EXPORT_LUT_33PTCUBE", "EXPORT_LUT_65PTCUBE", "EXPORT_LUT_PANASONICVLUT"]
CLOUD = [
    "CLOUD_SETTING_PROJECT_NAME", "CLOUD_SETTING_PROJECT_MEDIA_PATH", "CLOUD_SETTING_IS_COLLAB", "CLOUD_SETTING_SYNC_MODE",
    "CLOUD_SETTING_IS_CAMERA_ACCESS", "CLOUD_SYNC_NONE", "CLOUD_SYNC_PROXY_ONLY", "CLOUD_SYNC_PROXY_AND_ORIG",
    "CLOUD_SYNC_DEFAULT", "CLOUD_SYNC_DOWNLOAD_IN_QUEUE", "CLOUD_SYNC_DOWNLOAD_IN_PROGRESS", "CLOUD_SYNC_DOWNLOAD_SUCCESS",
    "CLOUD_SYNC_DOWNLOAD_FAIL", "CLOUD_SYNC_DOWNLOAD_NOT_FOUND", "CLOUD_SYNC_UPLOAD_IN_QUEUE", "CLOUD_SYNC_UPLOAD_IN_PROGRESS",
    "CLOUD_SYNC_UPLOAD_SUCCESS", "CLOUD_SYNC_UPLOAD_FAIL", "CLOUD_SYNC_UPLOAD_NOT_FOUND", "CLOUD_SYNC_SUCCESS",
]
MISC = ["DLB_BLEND_SHOTS"]

KNOWN_CONSTANTS = (
    EXPORT_TYPES + EXPORT_SUBTYPES + KEYFRAME_MODES + CACHE_MODES + MARKER_COLORS + SUBTITLE_KEYS + AUTO_CAPTION
    + AUDIO_SYNC + LUT_EXPORT + CLOUD + MISC
)
